spring.application.name=nexuserp
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:5244/nexuserp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=America/Sao_Paulo

app.jwt.secret=${JWT_SECRET:VGhpcy1pcy1hLXZlcnktbG9uZy1zZWNyZXQta2V5LWZvci1uZXh1c2VycC0yMDI2IQ==}
app.jwt.expiration=86400000
app.cors.allowed-origin=${FRONTEND_URL:http://localhost:5173}
