spring.application.name=prova-base
server.port=8080

# =========================================================
# BANCO PADRAO: MYSQL / MariaDB (visivel no phpMyAdmin)
# =========================================================
# Pode sobrescrever por variaveis de ambiente:
# DB_URL, DB_USER, DB_PASSWORD
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:5244/prova_base?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=${JWT_SECRET:troque-esta-chave-super-secreta-com-pelo-menos-32-caracteres-123456789}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

springdoc.swagger-ui.path=/swagger-ui.html
