package br.com.gestao.product;
import br.com.gestao.product.dto.ProductRequest; import br.com.gestao.stock.*; import org.springframework.http.*; import org.springframework.messaging.simp.SimpMessagingTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException; import java.time.LocalDateTime; import java.util.*;
@Service public class ProductService{
 private final ProductRepository repo; private final StockMovementRepository movements; private final SimpMessagingTemplate messaging;
 public ProductService(ProductRepository r,StockMovementRepository m,SimpMessagingTemplate s){repo=r;movements=m;messaging=s;}
 public List<Product> list(String search){return search==null||search.isBlank()?repo.findAll():repo.findByNameContainingIgnoreCaseOrderByName(search);}
 public Product find(Long id){return repo.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Produto não encontrado"));}
 @Transactional public Product create(ProductRequest q,String user){ if(repo.findBySkuIgnoreCase(q.sku()).isPresent()) throw new ResponseStatusException(HttpStatus.CONFLICT,"SKU já cadastrado"); Product p=new Product(null,q.sku(),q.name(),q.category(),q.costPrice(),q.salePrice(),q.stock(),q.minStock(),q.active()==null||q.active()); p=repo.save(p); if(p.getStock()>0) movements.save(new StockMovement(null,p.getId(),p.getName(),MovementType.ENTRY,p.getStock(),0,p.getStock(),"Estoque inicial",user,LocalDateTime.now())); notifyChange("PRODUCT_CREATED",p); return p; }
 @Transactional public Product update(Long id,ProductRequest q){ Product p=find(id); repo.findBySkuIgnoreCase(q.sku()).filter(x->!x.getId().equals(id)).ifPresent(x->{throw new ResponseStatusException(HttpStatus.CONFLICT,"SKU já cadastrado");}); p.setSku(q.sku());p.setName(q.name());p.setCategory(q.category());p.setCostPrice(q.costPrice());p.setSalePrice(q.salePrice());p.setMinStock(q.minStock());if(q.active()!=null)p.setActive(q.active()); Product saved=repo.save(p);notifyChange("PRODUCT_UPDATED",saved);return saved; }
 @Transactional public Product move(Long id,MovementType type,int qty,String note,String user){Product p=find(id);int old=p.getStock();int next=switch(type){case ENTRY->old+qty;case EXIT,SALE->old-qty;case ADJUSTMENT->qty;}; if(next<0) throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Estoque insuficiente");p.setStock(next);Product saved=repo.save(p);movements.save(new StockMovement(null,p.getId(),p.getName(),type,qty,old,next,note,user,LocalDateTime.now()));notifyChange("STOCK_CHANGED",saved);return saved;}
 @Transactional public void delete(Long id){Product p=find(id);if(p.getStock()>0)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Zere o estoque antes de excluir");repo.delete(p);notifyChange("PRODUCT_DELETED",p);} private void notifyChange(String a,Product p){messaging.convertAndSend("/topic/gestao",(Object) Map.of("action",a,"productId",p.getId()));}
}
