spring.datasource.password=
spring.mail.password=
jwt.secret=string_de_pelo_menos_32_caracteres
jwt.expiration=1000000
jwt.issuer=financeiro-backend

app.security.jwt.secret=${jwt.secret}
app.security.jwt.issuer=${jwt.issuer}
app.security.jwt.expiration-minutes=120