descricao.obrigatorio=Descrição é obrigatória
name.obrigatorio=Nome é obrigatório
email.obrigatorio=Email é obrigatório
email.invalido=Email inválido
password.obrigatorio=Senha é obrigatória
active.obrigatorio=Ativo é obrigatório